### ISSUE TITLE
feat: Please add 8K 10fps button

### ISSUE THREAD

**Issue by jcasman** [AirTechWick/expo-app-theta-x#1]
Even though it's not listed here (https://github.com/theta360developers/theta-javascript/tree/main/X-specific/low_fps_video) can you please create another button and update the react-native app?

**Comment by codetricity** [comment]
https://github.com/ricohapi/theta-api-specs/blob/main/theta-web-api-v2.1/options/file_format.md

```javascript
{"type": "mp4","width": 7680,"height": 3840, "_codec": "H.264/MPEG-4 AVC", "_frameRate": 10}
```

**Comment by AirTechWick** [comment]
Yes 👍

**Comment by AirTechWick** [comment]
Added in 4573bf2 commit
