### ISSUE TITLE
feat: change in button order

### ISSUE THREAD

**Issue by jcasman** [AirTechWick/expo-app-theta-x#2]
Please have first row have 4 buttons: IMG MODE, VID MODE, OFF CAM SRC, ON CAM SRC
Second row has 3 buttons: VID 5 MINS, VID 25 MINS, VID 2 HRS
Third row has 3 buttons: BIT RATE ECON, BIT RATE NORM, BIT RATE FINE
Fourth row has 3 buttons: 8K 2FPS, 8K 5FPS, 8K 10FPS
Fifth row has 3 buttons: 5.7K 2FPS, 5.7K 5FPS, 5.7K 10FPS

**Comment by AirTechWick** [comment]
Okay 👍

**Comment by AirTechWick** [comment]
Added in commit 0fe1fe5
